services:
    sha256salted_encoder:
          class: Wallabag\GroupBundle\Service\Sha256Salted

    wallabag_core.filter.type.entry:
            class: Wallabag\GroupBundle\Form\UserGroupType
            tags:
                - { name: form.type }